# Generated by Django 2.2.7 on 2020-09-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='theatersurls',
            table='theaters_urls',
        ),
    ]
